import { Component } from "react";

export const data = [
  {
    headComp:
      "font-mono font-bold tracking-wide animate-pulse line-clamp-5 md:text-7xl text-6xl mb-8",
    head: "Hellooo 👋",
    p1Comp:
      "font-mono tracking tracking-wide line-clamp-6 md:text-4xl text-3xl mb-2 ",
    p1: "I'm Alfian Hanif FY",
    p2Comp:
      "font-mono tracking tracking-wide line-clamp-5 md:text-2xl text-1xl",
    p2: "Teknik Informatika Ganesha",
  },
  {
    srcComp: "rounded-lg h-[210px] object-center",
    src: "/photo.png",
    alt: "foto diri",
  },
  {
    headComp: "font-mono font-bold  md:text-2xl text-xl mb-4 mt-4",
    head: "Interested in ...",
    p1Comp: "font-mono mb-2",
    p1: " - Software Engineer",
    p2Comp: "font-mono mb-2",
    p2: " - UI/UX",
    p3Comp: "font-mono mb-2",
    p3: " - Web Development",
    p4Comp: "font-mono mb-2",
    p4: " - Game Development",
  },
  {
    headComp: "font-mono font-bold  md:text-2xl text-xl mb-4 mt-4",
    head: "Talent ...",
    p1Comp: "font-mono mb-2",
    p1: " - Easy to enjoy somethin",
    p2Comp: "font-mono mb-2",
    p2: " - Can work with a team ",
    p3Comp: "font-mono mb-2",
    p3: " - Work well individual",
    p4Comp: "font-mono mb-2",
    p4: " - Fast learner ?",
  },
  {
    headComp:
      "font-mono font-bold tracking-wide  line-clamp-5 md:text-7xl text-6xl mb-8",
    head: "ABOUT ME !",
    p1Comp: "font-mono mb-8 md:text-3xl",
    p1: "Human who liked to explore New Technologies.",
    p2Comp: "font-mono mb-8 md:text-3xl",
    p2: "Someone who L̶i̶k̶e̶d̶ to design.",
    p3Comp: "font-mono mb-8 md:text-3xl",
    p3: "Person who still learn.",
    p4Comp: "font-mono mb-8 md:text-3xl",
    p4: "Enjoy every proccess.",
  },
  {
    headComp: "font-mono font-bold  md:text-2xl text-xl mb-4 mt-4",
    head: "Hobbies ...",
    p1Comp: "font-mono mb-2",
    p1: " - Game ",
    p2Comp: "font-mono mb-2",
    p2: " - Easy to enjoy somethin",
    p3Comp: "font-mono mb-2",
    p3: " - Can work with a team ",
    p4Comp: "font-mono mb-2",
    p4: " - Work well individual",
  },
  {
    headComp: "font-mono font-bold  md:text-2xl text-xl mb-4 mt-4",
    head: "Contact ...",
    p1Comp: "font-mono mb-2",
    p1: " - Game ",
    p2Comp: "font-mono mb-2",
    p2: " - Easy to enjoy somethin",
    p3Comp: "font-mono mb-2",
    p3: " - Can work with a team ",
    p4Comp: "font-mono mb-2",
    p4: " - Work well individual",
  },
  {
    headComp:
      "font-mono font-bold tracking-wide animate-pulse line-clamp-5 md:text-5xl text-4xl text-center",
    head: "Skill & Experience",
    p1Comp: "",
    p1: "",
    p2Comp: "",
    p2: "",
  },
];
